### ISSUE TITLE
Official Papirus for Android

### ISSUE THREAD

**Issue by limbusdev** [osmanonurkoc/papirusadaptive#3]
Just wanted to let you know, there is an official approach. Maybe you could join forces: https://github.com/PapirusDevelopmentTeam/papirus_icons.git

**Comment by osmanonurkoc** [comment]
Thank you for your offer.I would like to contribute in my spare time.

Georg Eckert <notifications@github.com>, 23 Oca 2021 Cmt, 12:49 tarihinde
şunu yazdı:

**Comment by limbusdev** [comment]
Its not my project. Just stumbled upon it and thought I'd let you know.

**Comment by osmanonurkoc** [comment]
Ok brother, that's my fault. I misunderstood. Thanks a lot anyway.
