### ISSUE TITLE
[Icon request] Freezer

### ISSUE THREAD

**Issue by julianfairfax** [osmanonurkoc/papirusadaptive#4]
Notice: I'm using this app on a phone with microG instead of Google Play Services, so I get an error relating to license when I open the app, and can't request an icon from there.

### Is your feature request related to a problem? Please describe.

The "problem" is that I have one of the apps I'm using (Freezer/f.f.freezer from https://files.freezer.life) doesn't have an icon

### Describe the solution you'd like

Add an icon for Freezer (f.f.freezer from https://files.freezer.life)

Thanks for developing this amazing app!

**Comment by julianfairfax** [comment]
This app doesn't seem to be in active development or following the Papirus Development Team's changes so I'm just going to consider this not going to happen.

**Comment by osmanonurkoc** [comment]
I'm sorry for the late reply. I stopped developing the app for now. Because I don't have time for this. But I will be releasing a final update soon. I will include your icon request in the update.  Also if we come to the microg problem,I don't know if I can fix it.  Thank you, have a nice day.

**Comment by julianfairfax** [comment]
> I'm sorry for the late reply. I stopped developing the app for now. Because I don't have time for this.

That's okay.

> But I will be releasing a final update soon. I will include your icon request in the update. 

Thank you.

> Also if we come to the microg problem,I don't know if I can fix it. Thank you, have a nice day.

Well your app checks if it was installed by com.android.vending, the app that I used to install it is com.aurora.store so you could add that, or since it's a free app, you could just remove that check?

**Comment by osmanonurkoc** [comment]
I'll disable license checker. Thanks for your advice.
