### ISSUE TITLE
f-droid inclusion + license issue

### ISSUE THREAD

**Issue by WPFilmmaker** [osmanonurkoc/papirusadaptive#5]
### Is your feature request related to a problem? Please describe.

At the moment there your icons pack is not on f-droid, an appstore for FLOSS apps.
### Describe the solution you'd like

Add your icons pack to f-droid, it is easy and can be done at https://gitlab.com/fdroid/rfp/-/issues where a nice community can assist you. Otherwise a user can request the inclusion but the author ought to be ok with that.
### Additional context

Also on github page you mention that the icon pack is licensed under GNU General Public License, however the license file says GNU Affero General Public License which are two different licenses, can you choose one?

**Comment by osmanonurkoc** [comment]
I solved the license conflict. But i have no plans for f-droid release. If anyone wants to publish on f-droid, I will not prevent it. Thank you for sharing opinions.
